workflows:
  macOS-workflow:
    name: macOS Workflow
    working_directory: src/app
    instance_type: mac_mini_m1
    max_build_duration: 10
    integrations:
      app_store_connect: Codemagic CI
    environment:
      flutter: 3.7.6
      xcode: latest
      cocoapods: default
      groups:
        - RANIERJARDIM_APP_STORE_CREDENTIALS
        - GENERAL
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Fetch Mac App Distribution certificate and Mac App Store profile
        script: |
          app-store-connect fetch-signing-files \
            $BUNDLE_ID \
            --platform MAC_OS \
            --type MAC_APP_STORE \
            --create
      - name: Fetch Mac Installer Distribution certificates
        script: |
          app-store-connect list-certificates --type MAC_INSTALLER_DISTRIBUTION --save || \
          app-store-connect create-certificate --type MAC_INSTALLER_DISTRIBUTION --save
      - name: Set up signing certificate
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      #- name: Flutter analyze
      #  script: |
      #    flutter analyze
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build Flutter macOS
        script: |
          flutter build macos --release
      - name: Package macOS application
        script: |
          set -x
          # Command to find the path to your generated app
          APP_NAME=$(find $(pwd) -name "*.app")
          cd $(dirname "$APP_NAME")
          PACKAGE_NAME=$(basename "$APP_NAME" .app).pkg
          # Create an unsigned package
          xcrun productbuild --component "$APP_NAME" /Applications/ unsigned.pkg
          # Find the installer certificate commmon name in keychain
          LISTA_CERTIFICADOS=$(keychain list-certificates)
          INSTALLER_CERT_NAME=$(keychain list-certificates \
            | jq '.[]
            | select(.common_name
            | contains("Apple Distribution"))
            | .common_name' \
            | xargs)
          # Sign the package
          xcrun productsign --sign "$INSTALLER_CERT_NAME" unsigned.pkg "$PACKAGE_NAME"
    artifacts:
      - build/macos/**/*.pkg
    publishing:
      email:
        recipients:
          - ranierjardim@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: true

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: false
