name: api_mocker_gateway
description: A REST API mocker for any app
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  yaml: ^3.1.1
  dcli: any
  conduit: ^3.0.0
  stubble: ^1.1.0
  accept_language_parser: ^1.0.1

dev_dependencies:
  test: ^1.16.5
  conduit_test: ^3.0.0
