name: api-mocker-gateway # you probably want to 'snapcraft register <name>'
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: A REST API mocker for any app # 79 char long summary
description: |
  A REST API mocker for any app

confinement: strict
base: core18
grade: stable
architectures:
  - build-on: [ amd64 ]
  - build-on: [ arm64 ]

slots:
  dbus-api-mocker-gateway:
    interface: dbus
    bus: session
    name: com.ranierjardim.amg

apps:
  api-mocker-gateway:
    plugs:
      - desktop
      - desktop-legacy
      - home
      - network
      - network-bind
      - removable-media
    slots:
      - dbus-api-mocker-gateway
    command: api_mocker_gateway
    extensions: [flutter-3.7.6]

parts:
  # Integrate custom dialogs in your snap - doc - snapcraft.io
  # https://forum.snapcraft.io/t/integrate-custom-dialogs-in-your-snap/10825
  zenity-integration:
    plugin: nil
    stage-snaps:
      - zenity-integration
  api-mocker-gateway:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application