name: api-mocker-gateway
adopt-info: info-from-environment-part
summary: A REST API mocker for any app
description: |
  A REST API mocker for any app

confinement: strict
base: core18
architectures:
  - build-on: [ amd64 ]
  - build-on: [ arm64 ]

apps:
  api-mocker-gateway:
    plugs:
      - desktop
      - desktop-legacy
      - home
      - network
      - network-bind
      - removable-media
      - gsettings
      - opengl
      - wayland
      - x11
    command: api_mocker_gateway
    extensions: [flutter-stable]

parts:
  # Integrate custom dialogs in your snap - doc - snapcraft.io
  # https://forum.snapcraft.io/t/integrate-custom-dialogs-in-your-snap/10825
  zenity-integration:
    plugin: nil
    stage-snaps:
      - zenity-integration
  api-mocker-gateway:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
  info-from-environment-part:
    source: .
    plugin: dump
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$APP_VERSION"
      snapcraftctl set-grade "$APP_GRADE"